### ISSUE TITLE
Husky unreliability

### ISSUE THREAD

**Issue by tgandrews** [ONSdigital/eq-author-app#106]
### Expected behaviour
pre-commmit hooks should work in all folders no matter the install order of the projects

### Actual behaviour
husky often fails with confusing error messages when trying to commit

### Steps to reproduce the behaviour
Depending on `yarn install` order on child projects this can be created

**Comment by adammahmood** [comment]
I've been having this issue recently.  Do we know any potential solutions?

**Comment by tgandrews** [comment]
Supposedly for @SamGodwin2 installing the packages in `api`, `frontend`, `publisher` worked for him.

I think the correct solution is to move it up to the top level instead of each project. This is probably true for a number of the packages but needs investigation.
