### ISSUE TITLE
Deleting a routing rules destination doesn't then update the destination. 

### ISSUE THREAD

**Issue by SamGodwin2** [ONSdigital/eq-author-app#180]
### Expected behaviour

1. Given 3 pages, 1,2 and 3.
2. Make page 1 route to 3.
3. Delete page 3.
4. Navigate back to page 1's routing.
5. Page 1 should now be routing to the next page.

### Actual behaviour

Given the steps above when you reach step 5 the app will crash due to the destination no longer being valid.

**Comment by pricea1** [comment]
Fixed by
https://trello.com/c/2KGXE7Zd/1214-eq-author-app-180-deleting-a-routing-rules-destination-doesnt-then-update-the-destination-issue
