### ISSUE TITLE
Content picker overflowing when large number of options.

### ISSUE THREAD

**Issue by SamGodwin2** [ONSdigital/eq-author-app#189]
### Expected behaviour
The content picker modal should scroll when there is a large number of options inside the accordion.
 
### Actual behaviour
The accordion panel just expands until it starts overflowing the modal.

### Steps to reproduce the behaviour
Make a questionnaire with <10 pages, on the first page go to routing and open the destination content picker. Select the destinations in this section and observe...

### Screenshot

![screenshot 2019-02-05 at 14 47 01](https://user-images.githubusercontent.com/35268220/52281148-60881200-2955-11e9-9dd9-c8704b97f8ef.png)

**Comment by tgandrews** [comment]
I wonder if this is another 72 issue as it used to scroll. As it definitely used to for the piping version as the answer picker doesn't actually have a lot of height when you are drilling down.

**Comment by tgandrews** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chrome 72 layout bugs](https://trello.com/c/nBzWIEQk/920-chrome-72-layout-bugs)

**Comment by tgandrews** [comment]
This is resolved in Chrome 74 
<img width="1140" alt="screenshot 2019-02-07 at 11 58 16" src="https://user-images.githubusercontent.com/180903/52410247-aec12080-2acf-11e9-8fea-b50379cc62e5.png">

So not our bug to fix.

**Comment by tgandrews** [comment]
Reading more into the issue it was changed to improve compatibility with other browsers so we should apply the suggested fix as well.
