### ISSUE TITLE
Visual bug ghosting on properties panel

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-author-app#276]
I've noticed a weird visual bug after moving answers, deleting an answer and then deleting a page.

### Expected behaviour
User does not see the ghost remnants of the answers

### Actual behaviour
Ghost image of deleted answers are visible to the user.
A refresh is required to get rid of the ghost image.

### Steps to reproduce the behaviour
Create a questionnaire.
Add three answers (tested with three currency answers)
~Move one of the answers down/up~
Delete the middle answer
Delete the page.

### Technical information
Tested on chrome in staging environment.

#### Browser
Chrome  72.0.3626.121

#### Operating System
Mac OS X Mojave

### Screenshot
![image](https://user-images.githubusercontent.com/4097796/54820108-f07be400-4c95-11e9-8406-78d3dd1c0d1b.png)

**Comment by tgandrews** [comment]
You do not need to move an answer to recreate. You just need to delete the middle answer.

But it looks like a Chrome bug

**Comment by samiwel** [comment]
Yeah I thought as much, we've seen similar weird ghosting behaviour in the past. IIRC adding a `postion: relative` fixed it in other places.

**Comment by pricea1** [comment]
Fixed by https://github.com/ONSdigital/eq-author-app/pull/287
