### ISSUE TITLE
Moving a question referenced in a routing to after the reference crashes the app.

### ISSUE THREAD

**Issue by SamGodwin2** [ONSdigital/eq-author-app#280]
### Expected behaviour
Given 2 sections each with a page and a number answer.
Make a routing rule on section 2 page 1 which references the answer in Section 1 page 1.
Move section 1 to after Section 2
The answer selector in the routing on Section 2 Page 1 should have the default `please select` selected.

### Actual behaviour
App crashes...

### Steps to reproduce the behaviour
See above

#### Browser
Chrome
#### Operating System
Mac

**Comment by jchapman68** [comment]
Could not reproduce the error - maybe fixed as consequence of other changes.

**Comment by heofs** [comment]
I could not reproduce this either, @SamGodwin2 can we close this?

**Comment by MattElcock** [comment]
Closed as two devs couldn't reproduce the issue; @SamGodwin2 if you want this reopened let us know.
