### ISSUE TITLE
Lots of delete confirm elements on questionnaire list page

### ISSUE THREAD

**Issue by tgandrews** [ONSdigital/eq-author-app#318]
### Steps to reproduce the behaviour
1. Visit the questionnaire list page
2. Expect to see at most 1 delete confirm dialog in the DOM
3. Actually see a large number of them

### Screenshot
![Screenshot 2019-04-17 at 09 00 57](https://user-images.githubusercontent.com/180903/56271022-66396b00-60ef-11e9-962e-bbc666dc6d95.png)

**Comment by pricea1** [comment]
https://trello.com/c/3VH8kS1K/1060-eq-author-app-318-lots-of-delete-confirm-elements-on-questionnaire-list-page-issue

**Comment by pricea1** [comment]
https://github.com/ONSdigital/eq-author-app/pull/322
