### ISSUE TITLE
Mutually exclusive options being returned with all other options.

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-author-app#336]
### Expected behaviour
Mutually exclusive options should not be resolved with the list of regular options.

### Actual behaviour
Mutually exclusive options are being returned with the list.

### Steps to reproduce the behaviour
Add a checkbox answer to a page.
Add a single option.
Add a mutually exclusive option.
Refresh the page.
The page will contain three options.
(The mutually exclusive option is duplicated).

### Technical information
Discovered in production, but has been recreated in staging environment.

#### Browser
Chrome.

#### Operating System
N/A

### Screenshot
![image](https://user-images.githubusercontent.com/4097796/57538862-2c036800-7341-11e9-8caa-97be1f67bcde.png)

**Comment by pricea1** [comment]
Fixed by https://github.com/ONSdigital/eq-author-app/commit/dbf3e4bb738c61b91de1363aad355b98745cbe6f
