### ISSUE TITLE
Highlighting in title not shown on calculated summary page

### ISSUE THREAD

**Issue by samiwel** [ONSdigital/eq-author-app#343]
### Expected behaviour
Highlighting in calculated summary title should either be displayed, or the option to add highlighting to a calculated summary title should not be present.

### Actual behaviour
It is possible to apply highlighting within Author, but these changes are not displayed on launching the questionnaire in Runner.

### Steps to reproduce the behaviour
Add a few pages with number answers.
Add a calculated summary page.
In the title of the calculated summary page, use the rich text editor to highlight some of the content.
Preview/launch the questionnaire.
Observe that the highlighting is not visible on the calculated summary page.

highlighting applied to any of the question pages leading up to the calculated summary page is shown.

### Technical information
Reproduced in staging.
Seems that <em> tags are being applied to the title, which could indicate that the required styles to highlight the text are not available for calculated summary titles. See `templates/summary.html` line 41 in eq-survey-runner.

#### Browser
Chrome  73.0.3683.103

#### Operating System
macOS Mojave 10.14.4

### Screenshot
![image](https://user-images.githubusercontent.com/4097796/57776692-0ea31500-7718-11e9-9519-77efbc49e63d.png)

**Comment by pricea1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Highlighting in title not shown on calculated summary page on runner](https://trello.com/c/O3HHKy2o/1120-highlighting-in-title-not-shown-on-calculated-summary-page-on-runner)
