### ISSUE TITLE
Datastore - Incorrect array merges

### ISSUE THREAD

**Issue by tgandrews** [ONSdigital/eq-author-app#345]
### Steps to reproduce the behaviour
- Using UI - unknown
- Hitting `/graphql` - unknown
- Unit test
```javascript
it("should merge array changes correctly", async () => {
  const mergeResult = await getMergeResult(
    // Remove 2
    {
      id: "someId",
      metadata: [{ id: "1" }, { id: "3" }],
      sections: [],
      updatedAt: new RealDate("2012-01-01T10:00:00Z"),
      [originalKey]: {
        updatedAt: new RealDate("2012-01-01T10:00:00Z"),
        id: "someId",
        metadata: [{ id: "1" }, { id: "2" }, { id: "3" }],
        sections: [],
      },
    },
    // Remove 1
    {
      id: "someId",
      metadata: [{ id: "2" }, { id: "3" }],
      sections: [],
      updatedAt: new RealDate("2012-01-01T11:00:00Z"),
    }
  );

  expect(mergeResult).toEqual({
    id: "someId",
    metadata: [{ id: "3" }],
    sections: [],
    updatedAt: new RealDate(dateString),
  });
});
```

### Technical information
When multiple changes to something stored in the questionnaire as an array happen in quick succession then our implementation of generating patches and merging those into the updated object fails.

**Comment by tgandrews** [comment]
Now that we have `createMutation` this error could be bubbled out of the datastore and the whole mutation re-run on the new questionnaire state. This would remove any need to calculate and apply diffs.

**Comment by MattElcock** [comment]
Looks like work has been done on this and it's quite old now so I'll go ahead and close it.
