### ISSUE TITLE
Numeric answer validation — min value not clear to users

### ISSUE THREAD

**Issue by hamishtaplin** [ONSdigital/eq-author-app#484]
### Expected behaviour

When using a numeric answer, not adding a "min value" validation should not result in minimum value validation beyond the "system" minimum of -9999999 (or whatever it is)

### Actual behaviour

Adding a numeric answer but no "min value" validation results in the minimum acceptable value being 0.

### Steps to reproduce the behaviour

1. Add a numeric answer, with a label
1. Press "view survey"
1. Enter a value of `-1`

### Screenshot

<img width="1080" alt="Screenshot 2019-07-10 at 14 03 11" src="https://user-images.githubusercontent.com/930398/60971185-7f7f3b80-a31b-11e9-9b8c-b1771d40bd65.png">

**Comment by pricea1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Numeric answer validation — min value not clear to users](https://trello.com/c/AQc75FbO/1213-numeric-answer-validation-min-value-not-clear-to-users)

**Comment by MattElcock** [comment]
Looks like work on this has already been done. Although, this isn't an issue with Author but instead an issue with Runner. For those reasons, I'm going to go ahead and close this.
