### ISSUE TITLE
Non existent survey link doesn't re-direct to a 404 error.  

### ISSUE THREAD

**Issue by rmccar** [ONSdigital/eq-author-app#5]
### **Expected behaviour**
If you try to enter the url of a questionnaire page that doesn't exist using the Mock API you should be redirected to a 404 error.

### **Actual behaviour**
Instead the page never loads and if you delete the mockDataStore then reload the page you get a "TypeError: Cannot read property 'sections' of null"

### **Steps to reproduce the behaviour**
Create a new survey, change the url to something like /#/questionnaire/1/design/5/3, the page wont load, so if you delete the mockDataStore then reload the page you sent sent to the sign in page which when you press the button returns you to the faulty url and shows the "TypeError: Cannot read property 'sections' of null".

### **Technical information**
For reference, the issue is also observed in pre-prod, so this is not specific to the mockAPI implementation. It will also happen when running against the real API.

**Browser**
Chrome

**Operating System**
**Screenshot**
![image](https://user-images.githubusercontent.com/42928680/48557527-ed837800-e8de-11e8-9a28-995e891cc0de.png)

**Comment by tgandrews** [comment]
Can no longer recreate after #299
